# Generated by Django 2.0.6 on 2018-07-26 19:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_assigner', '0003_auto_20180629_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='blocked_assignees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, help_text='Comma seperated usernames of members for whom assignmentshould be blocked', size=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='blocked_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, help_text='Comma seperated labels of issues for which assignmentshould be blocked', size=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='difficulty_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, help_text='Comma seperated labels of issues representing order ofdifficulty level of an issue in ascending order', size=None),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_assign_request',
            field=models.BooleanField(default=False, help_text='Assign issue if any member comments on an issue requesting for assignment to the issue.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='label_numbers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Max number(values) of issues with label (keys) a member can work on to be set; e.g. difficulty/newcomer: 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='org_level',
            field=models.BooleanField(default=False, help_text='Consider number of issues across all repositories within the entire organization'),
        ),
    ]
