image: docker:stable

services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - release

before_script:
  - export PATH=$(pwd)/.ci:$PATH
  - apk add --no-cache bash

.ee_options: &ee_options
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  only:
    - branches@gitmate/open-source/gitmate-2

build_image:
  stage: build
  script: "build_image"

build_ee_image:
  <<: *ee_options
  stage: build
  script: "build_image -ee"

run_tests:
  stage: test
  services:
    - docker:stable-dind
    - postgres:9-alpine
  script: "test_image"
