# Generated by Django 2.0.7 on 2018-11-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0025_auto_20180606_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_issue_weight_presence', models.BooleanField(default=False, help_text='Checks for presence of a weight on newly opened issues')),
                ('no_weight_label', models.TextField(default='dev/missing-weight', help_text='The label used to indicate that an issue was not associatedwith a weight')),
                ('check_overweight_issues', models.BooleanField(default=True, help_text='Check for issues having too much weight')),
                ('max_issue_weight', models.IntegerField(default=4, help_text='The maximum weight that can be assigned to an issue')),
                ('max_weight_label', models.TextField(default='dev/over-weight', help_text='The label used to indicate that an issue has too muchweight and needs to be broken down into smaller chunks')),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_weighing_machine_settings', to='gitmate_config.Repository')),
            ],
            options={
                'verbose_name_plural': 'settings',
                'abstract': False,
            },
        ),
    ]
