# Generated by Django 2.0.7 on 2018-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_weighing_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_weight_label',
            field=models.TextField(default='weight/overweight', help_text='The label used to indicate that an issue has too muchweight and needs to be broken down into smaller chunks'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='no_weight_label',
            field=models.TextField(default='weight/missing', help_text='The label used to indicate that an issue was not associatedwith a weight'),
        ),
    ]
