# Generated by Django 2.0.7 on 2018-11-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0025_auto_20180606_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_namespace', models.TextField(default='dev', help_text='The namespace under which current scrum process resides.')),
                ('ongoing_label', models.TextField(default='ongoing', help_text='The label which identifies a process as in progress.')),
                ('review_label', models.TextField(default='code-review', help_text='The label which identifies the process as in code review.')),
                ('acceptance_label', models.TextField(default='acceptance-QA', help_text='The label which identifies the process as requiring acceptance testing.')),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_scrum_settings', to='gitmate_config.Repository')),
            ],
            options={
                'verbose_name_plural': 'settings',
                'abstract': False,
            },
        ),
    ]
