# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 05:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plugins.gitmate_pr_rejector.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0024_delete_plugin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=plugins.gitmate_pr_rejector.models.default_branch, help_text='Automatically close pull requests opened from thesespecified branches of forks.', size=None)),
                ('message', models.TextField(default='Open PR on a different source branch other than master.', help_text='Comment this message when someone open PR onspecified branch')),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_pr_rejector_settings', to='gitmate_config.Repository')),
            ],
            options={
                'verbose_name_plural': 'settings',
                'abstract': False,
            },
        ),
    ]
